<?xml version="1.0"?>
<!DOCTYPE bookstore [
<!ELEMENT bookstore ((book)+)>
<!ELEMENT book (title,author,genre?)>
<!ELEMENT author (first-name,last-name)>
<!ELEMENT first-name (#PCDATA)>
<!ELEMENT last-name (#PCDATA)>

<!ELEMENT title (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ATTLIST book price CDATA #REQUIRED>
<!ATTLIST book ISBN CDATA #REQUIRED>
<!ATTLIST book publicationdate CDATA #IMPLIED>

]
>
<bookstore>
<book price="730.54" ISBN="string" publicationdate="2016-02-27">
<title>string</title>
<author>
<first-name>string</first-name>
<last-name>string</last-name>
</author>
<genre>string</genre>
</book>
<book price="6738.774" ISBN="string">
<title>string</title>
<author>
<first-name>string</first-name>
<last-name>string</last-name>
</author>
</book>
</bookstore>